name: tarsier_websocket_client
description: A Dart package for managing WebSocket connections and real-time event handling.
version: 1.0.0-dev
repository: https://github.com/marianz-bonfire/tarsier_websocket_client
homepage: https://github.com/marianz-bonfire/tarsier_websocket_client
issue_tracker: https://github.com/marianz-bonfire/tarsier_websocket_client/issues

environment:
  sdk: ^3.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

dependencies:
  async: ^2.11.0
  crypto: ^3.0.3
  http: ^1.2.0
  meta: ^1.10.0
  pinenacl: ^0.5.1
  stream_channel: ^2.1.2
  uuid: ^4.5.1

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

screenshots:
  - description: The package logo.
    path: assets/logo.png