name: tarsier_websocket_client
description: A starting point for Dart libraries or applications.
version: 1.0.0-dev
repository: https://github.com/marianz-bonfire/tarsier_websocket_client
homepage: https://github.com/marianz-bonfire/tarsier_websocket_client
issue_tracker: https://github.com/marianz-bonfire/tarsier_websocket_client/issues

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  meta: ^1.16.0
  pinenacl: ^0.5.1
  uuid: ^4.2.2
  web_socket_client: ^0.1.0-dev.1

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux: