# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart CI

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ '**.md', 'example/**' ]
  pull_request:
    branches: [ "master" ]
    paths-ignore: [ '**.md', 'example/**' ]
  schedule:
    # Runs at 00:00 UTC on the 1, 8, 15, 22 and 29th of every month.
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  build-dart:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        sdk: [ beta, stable, 3.2.1 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart version
        run: dart --version

      - name: Format code
        #if: ${{ matrix.sdk == 'stable' }}
        run: dart format .

      - name: Active coverage
        run: dart pub global activate coverage

      - name: Run tests
        run: dart run test

      - name: Install Codecov requirements using pytest
        run: pip install pytest pytest-cov

      - name: Run tests and generate a coverage report
        run: pytest --cov-branch --cov-report=xml
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: marianz-bonfire/pubspec_checker
